apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-transformer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-transformer
  template:
    metadata:
      labels:
        app: text-transformer
    spec:
      containers:
        - name: text-transformer
          image: gcr.io/sit323-23t1-bajaj-cd57acc/text-transformer:latest
          ports:
            - containerPort: 3000
